FROM php:8.1-cli-alpine

RUN apk update && apk add --no-cache \
    git \
    && rm -rf /var/cache/apk/ \
    && rm -rf /root/.cache \
    && rm -rf /tmp/*

RUN git clone --no-tags --single-branch --depth=1 https://github.com/vrana/adminer.git /app
WORKDIR /app
COPY ./overrides/* /app
# RUN git config protocol.git never
RUN git submodule update --init --recursive --single-branch --depth=1

RUN php compile.php