name: Build & Push Images

on:
  push:
    branches: [main]
    paths:
      - "Dockerfile.*"
      - ".github/workflows/**"
  workflow_dispatch:

env:
  IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}/adminer

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: Dockerfile.mysql-nginx
            version: "mysql"
            flavor: "nginx"
          - dockerfile: Dockerfile.mysql-standalone
            version: "mysql"
            flavor: "standalone"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REPO }}
          tags: |
            type=raw,value=${{ matrix.version }}-${{ matrix.flavor }}

      - name: Build & push ${{ matrix.version }}-${{ matrix.flavor }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          platforms: linux/amd64,linux/arm64
          push: true
          sbom: true
          provenance: mode=max
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      # - name: Slim it!
      #   uses: kitabisa/docker-slim-action@v1
      #   env:
      #     DSLIM_HTTP_PROBE: false
      #   with:
      #     target: ${{ env.IMAGE_REPO }}:${{ matrix.version }}-${{ matrix.flavor }}
      #     tag: "${{ matrix.version }}-${{ matrix.flavor }}-slim"

      # - name: Push slim image
      #   run: |
      #     docker push ${{ env.IMAGE_REPO }}:${{ matrix.version }}-${{ matrix.flavor }}-slim
